[install]
is_configured = 1

[ui]
is_visible = 1
label = Caprine Clinic

[launcher]
author = James Hodgkinson
description = Compare Splunk searches and inspect their results and job costs.
version = 0.1.0

[id]
name = caprine_clinic
version = 0.1.0

[package]
id = caprine_clinic
check_for_updates = 0
